cd Client_1\bin\Debug
start Client_1.exe
cd ..\..\..
cd Client3\bin\Debug
start Client3.exe
cd ..\..\..
cd TestHarness\bin\Debug
start TestHarness.exe
cd ..\..\..
cd Repository\bin\Debug
start Repository.exe
cd ..\..\..